### ISSUE TITLE
Create own dataset

### ISSUE THREAD

**Issue by HenriqueVarellaEhrenfried** [benedekrozemberczki/GAM#13]
Hello,

I would like to test you code with my own dataset, however, I did not undestand the format of it, specially the label key . In your README yo say that 

> **labels key** has a dictonary value for each node, these labels are stored as key-value pairs (e.g. node - atom pair)

Can the labels be strings? If the label must be numbers, why is the labels needed as a dictionary? I mean, could not it be a list of the nodes? It is all confusing for me. Could you explain it please? Pehaps you could create an image of the graph you are representing in your example of the README. I think that a image would clarify how the json can be made.

**Comment by benedekrozemberczki** [comment]
You can create a PR if you need it. I can imagine that you are able to do it if you need it.

https://gist.github.com/richhickey/1563cddea1002958f96e7ba9519972d9
