### ISSUE TITLE
Run the code error：The number of graph classes is: 0.

### ISSUE THREAD

**Issue by YoungBx** [benedekrozemberczki/GAM#14]
Can you help me solve the error " 
Collecting unique node labels.
0it [00:00, ?it/s]
The number of graph classes is: 0.
Training started.
0it [00:00, ?it/s] 
ZeroDivisionError: division by zero
Epoch:   0%|  
"when i run the code?
Thank U very much.

**Comment by benedekrozemberczki** [comment]
Could yo be more specific?
