### ISSUE TITLE
ImportError: cannot import name 'parameter_parser'

### ISSUE THREAD

**Issue by acecreamu** [benedekrozemberczki/GAM#2]
I had this issue with import:

```
File "src/main.py", line 1, in <module>
    from parser import parameter_parser
ImportError: cannot import name 'parameter_parser'
```

I solved it by renaming parser.py (e.g. my_parser.py) and calling `from my_parser import parameter_parser`
No problems anymore, just that it may be helpful for others.

**Comment by benedekrozemberczki** [comment]
If You want You can open a pull request.

**Comment by realFLUENCER** [comment]
Hey man, thanks for the insight!
Can you please explain how you renamed your parser?
