### ISSUE TITLE
[IndexError] Mismatched node label indexing? 

### ISSUE THREAD

**Issue by silent567** [benedekrozemberczki/GAM#4]
Hi, thanks for sharing the codes. 

I want to test GAM on my own dataset and encountered the IndexError. This is my simplied dataset: https://drive.google.com/file/d/1P2Z0i86ffF0dMq4OXcRPR2Icj4pvZ1WP/view?usp=sharing 

Is there any problem of the generated dataset? The node labels are actually the node degree and the sizes of graphs are always 50. 

I have tried to debug and found the most relevant codes: line [45](https://github.com/silent567/GAM/blob/bcb3d12849ba0df6f86b9bbcc1aba22225052353/src/gam.py#L45)-[75](https://github.com/silent567/GAM/blob/bcb3d12849ba0df6f86b9bbcc1aba22225052353/src/gam.py#L75) in src/gam.py . I am suspending that the indexing of labels in `self.identifiers`, `labels`, and `inverse_labels` are mismatched. In detail, the return label of function `sample_node_label` is not in the same domain of `labels.keys()`. They are referring to different mappings of the labels. 

Actually, I have changed the `labels[str(label)]` in line [73](https://github.com/silent567/GAM/blob/bcb3d12849ba0df6f86b9bbcc1aba22225052353/src/gam.py#L73) and [74](https://github.com/silent567/GAM/blob/bcb3d12849ba0df6f86b9bbcc1aba22225052353/src/gam.py#L74) to `label` . There is no bug afterwards. But I am not sure if the change is correct. 

Could you help me with this debug? Thank you!

**Comment by benedekrozemberczki** [comment]
Can You test it on the sample dataset with the modification?
Can you send me a copy of the modified code?

**Comment by silent567** [comment]
Hi, thank you for response and sorry for replying late. 

I have tested on the sample dataset. No error encounted. 
And for the modified code, here is my forked repo and the modification commit: https://github.com/silent567/GAM/commit/c5abdec8fd29c954f6d0628010ae9f70ea7bd6ec
