### ISSUE TITLE
ZeroDivisionError:division by zero

### ISSUE THREAD

**Issue by yy1335574510** [benedekrozemberczki/GAM#7]
![image](https://user-images.githubusercontent.com/51071665/60571111-84853d80-9da5-11e9-811e-ce578c40e5db.png)

**Comment by benedekrozemberczki** [comment]
The glob.glob() call does not see the files.

**Comment by camellia2** [comment]
Sorry I saw this problem now, the reason for this error is that the author assigns 0 to the values ​​of self.enpoch_loss and self.nodes_process, in gam.py file. I would like to ask if you know how these two values ​​should be set？ I found that they will affect the result result
